### ISSUE TITLE
Moving bed

### ISSUE THREAD

**Issue by JensLarsson** [PretentiousPanda/Alex#12]
I Ash rum fins det en dialog som byter ut spriten till sängen från den obäddade till den bäddade, pixlarnas position i de båda bilderna machar dock inte perfekt vilket får det att se ut som att sängen flyttar sig. 

Oklart i fall detta fixas av Grafik eller via kod, eller om det ska lämnas som det är

**Comment by Ekkara** [comment]
ett annat problem kring detta är att om man lämnar rummet så blir sängen obäddad  

edit man kan även starta dialogen vilket inte hade kanske varit det värsta men när alex lämnar rummet svarar han fortfarande
